# hello-mm/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-mm-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: hello-mm-sa
  namespace: default
roleRef:
  kind: Role
  name: hello-mm-role
  apiGroup: rbac.authorization.k8s.io
